from decimal import Decimal, InvalidOperation, ROUND_HALF_UP

from model.raw_input_model import RawStockRow, RawDemandRow
from model.internal_model import (
    NormalizationWarning, 
    NormalizeOptions, 
    SolveOptions, 
    NormalizationResult,
    NormalizedInput,
    DemandItem,
    StockItem
)


def normalize_inputs(
    raw_demands: list[RawDemandRow],
    raw_stocks: list[RawStockRow],
    normalize_options: NormalizeOptions,
    solve_options: SolveOptions,
) -> NormalizationResult:
    """
    Normalized the input data

    Args:
        raw_demands (list[RawDemandRow]): list of raw demands.
        raw_stocks (list[RawStocksRow]): list of raw stocks.
        normalized_options (NormalizeOptions): option for data normalization.
        solve_options (SolveOptions): Option for solver to be normalized.
    Returns:
        NormalizationResult: container of normalized data & warnings.
    """

    # normalize demand rows
    normalized_demands = []
    demand_warnings = []
    for row, demand in enumerate(raw_demands):
        row += 1
        item, warning = normalize_demand_row(demand, row, normalize_options.max_precision)
        normalized_demands.append(item)
        demand_warnings.extend(warning)

    # normalize stock rows
    normalized_stocks = []
    stock_warnings = []
    for row, stock in enumerate(raw_stocks):
        row += 1
        item, warning = normalize_stock_row(stock, row, normalize_options.max_precision)
        normalized_stocks.append(item)
        stock_warnings.extend(warning)
       
    # parse kerf
    kerf, kerf_is_rounded = parse_decimal(solve_options.kerf, normalize_options.max_precision)
    # print(f"kerf = {kerf} - {kerf_is_rounded}")

    # collect all decimals
    decimals = [x["length"] for x in normalized_demands] + [x["length"] for x in normalized_stocks] + [kerf]
    # print(f"list of decimal = {decimals}")

    # detect global unit_scale
    unit_scale = detect_scale(decimals)

    # convert Decimal → int
    kerf = int(kerf * unit_scale)

    # build canonical dataclass
    warnings = []

    demands = []
    for demand in normalized_demands:
        demand_items = DemandItem(
            id          = demand["id"], 
            group       = demand["group"], 
            length      = int(demand["length"] * unit_scale),
            quantity    = demand["quantity"]
            )
        demands.append(demand_items)

    stocks = []
    for stock in normalized_stocks:
        stock_items = StockItem(
            id          = stock["id"], 
            group       = stock["group"], 
            length      = int(stock["length"] * unit_scale),
            quantity    = stock["quantity"]
            )
        stocks.append(stock_items)

    warnings.extend(demand_warnings)
    warnings.extend(stock_warnings)

    if kerf_is_rounded:
        warnings.append(NormalizationWarning("Kerf is rounded", 0))

    data = NormalizedInput(
        demands = demands,
        stocks = stocks,
        kerf = kerf,
        unit_scale = unit_scale
    )

    # return result
    return NormalizationResult(data, warnings)
    

def normalize_demand_row(
    row: RawDemandRow,
    row_number: int,
    max_precision: int,
) -> tuple[dict, list[NormalizationWarning]]:
    item_id, id_warning = normalize_id(row.id, "part", row_number)
    group, group_warning = normalize_group(row.group)
    length, length_warning = parse_decimal(row.length, max_precision)
    quantity = parse_quantity(row.quantity)

    if length <= 0:
        raise NormalizationError("Length must be greater than zero", "length", row)
    
    data = {
        "id": item_id,
        "group": group,
        "length": length,
        "quantity": quantity
    }

    warnings = []
    if id_warning:
        warnings.append(NormalizationWarning("ID autogenerated", row))
    if group_warning:
        warnings.append(NormalizationWarning("Group defaulted", row))
    if length_warning:
        warnings.append(NormalizationWarning("Length rounded", row))
    if quantity == 0:
        warnings.append(NormalizationWarning("qty is zero", row))

    return data, warnings

def normalize_stock_row(
    row: RawStockRow,
    row_number: int,
    max_precision: int,
) -> tuple[dict, list[NormalizationWarning]]:
    item_id, id_warning = normalize_id(row.id, "stock", row_number)
    group, group_warning = normalize_group(row.group)
    length, length_warning = parse_decimal(row.length, max_precision)
    quantity = parse_quantity(row.quantity)

    if length <= 0:
        raise NormalizationError("Length must be greater than zero", "length", row)
    
    data = {
        "id": item_id,
        "group": group,
        "length": length,
        "quantity": quantity
    }

    warnings = []
    if id_warning:
        warnings.append(NormalizationWarning("ID autogenerated", row))
    if group_warning:
        warnings.append(NormalizationWarning("Group defaulted", row))
    if length_warning:
        warnings.append(NormalizationWarning("Length rounded", row))
    if quantity == 0:
        warnings.append(NormalizationWarning("qty is zero", row))

    return data, warnings

def detect_scale(value: list[Decimal]) -> int:
    max_decimal = 0

    for v in value:
        decimals = max(0, -v.as_tuple().exponent)
        max_decimal = max(max_decimal, decimals)
        
    return 10 ** max_decimal

def parse_quantity(raw: str) -> int:
    try:
        value = Decimal(raw.replace(",", "."))
    except InvalidOperation as exc:
        raise NormalizationError(f"Invalid quantity: {raw!r}") from exc
    
    if value < 0:
        raise NormalizationError(f"Quantity must not be negative: {raw!r}")
    
    if value != value.to_integral_value():
        raise NormalizationError(f"Quantity contains non-zero decimals: {raw!r}")
    
    return int(value)

def parse_decimal(raw: str, max_precision: int = 28) -> tuple[Decimal, bool]:
    try:
        value_raw = Decimal(raw.replace(",", "."))
    except InvalidOperation as exc:
        raise NormalizationError(f"Invalid numeric value: {raw!r}") from exc
    
    quant = Decimal("1").scaleb(-max_precision)
    value = value_raw.quantize(quant, rounding=ROUND_HALF_UP)
    value = value.normalize()

    is_rounded = value != value_raw

    return value, is_rounded
    
def normalize_group(raw: str) -> tuple[str, bool]:
    value = raw.strip()
    is_default = value == ""
    if is_default:
        value = "default"

    return value, is_default

def normalize_id(raw: str, prefix: str, index: int) -> tuple[str, bool]:
    value = raw.strip()
    is_autogenerated = value == ""
    if is_autogenerated:
        value = f"{prefix}-{index:04d}"

    return value, is_autogenerated


class NormalizationError(ValueError):
    """Raised when input normalization fails."""
    def __init__(self, message: str, field: str | None = None, row: int | None = None):
        self.field = field
        self.row = row
        super().__init__(message)